# Generated by Django 4.1.5 on 2023-03-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link_to_classroom',
            field=models.URLField(null=True),
        ),
    ]
