# Generated by Django 4.1.5 on 2023-03-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='discount_paypal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
