# Generated by Django 4.1.5 on 2023-03-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_alter_career_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre. Intente con otro.'}, max_length=150, unique=True),
        ),
    ]
