# Generated by Django 4.1.7 on 2023-03-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='code_meeting',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
