# Generated by Django 4.1.5 on 2023-03-14 20:32

import Apps.Eventos.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0003_alter_career_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=Apps.Eventos.models.event_directory_logo_path, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg'])]),
        ),
    ]
