# Generated by Django 4.2.1 on 2023-05-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0003_event_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
    ]
