# Generated by Django 4.1.7 on 2023-03-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0003_event_code_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='platform_meeting',
            field=models.CharField(choices=[('Zoom', 'Zoom'), ('Google Meet', 'Google Meet'), ('Microsoft Teams', 'Microsoft Teams'), ('Discord', 'Discord'), ('Skype', 'Skype')], max_length=20, null=True),
        ),
    ]
