# Generated by Django 4.1.5 on 2023-03-15 16:31

import Apps.Eventos.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0005_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='curriculum_user',
            field=models.FileField(max_length=255, upload_to=Apps.Eventos.models.event_directory_user_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_planning',
            field=models.FileField(max_length=255, upload_to=Apps.Eventos.models.event_directory_planning_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
