# Generated by Django 4.2.1 on 2023-05-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappcontact',
            old_name='country_of_birth',
            new_name='country',
        ),
    ]
