# Generated by Django 4.2.1 on 2023-05-22 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_country_of_birth_whatsappcontact_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailContact',
            new_name='EmailContactEvent',
        ),
    ]
