# Generated by Django 4.1.7 on 2023-04-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_referral',
            field=models.BooleanField(default=False),
        ),
    ]
