# Generated by Django 4.1.7 on 2023-04-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0003_participant_referral'),
        ('Users', '0002_user_is_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='interests', to='Eventos.career'),
        ),
    ]
